---
- name: Remove samba if installed ...
  apt:
    pkg: ['samba-common-bin', 'samba-common', 'samba-dsdb-modules', 'samba-libs smbclient']
    state: absent

- name: Increase Kernel default rx buffersize
  sysctl:
    name: net.core.rmem_default
    value: 26214400
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Increase Kernel max rx buffersize
  sysctl:
    name: net.core.rmem_max
    value: 26214400
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Increase Kernel max optmem buffersize
  sysctl:
    name: net.core.optmem_max
    value: 81920
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Increase max queue len of unhandled rx packets in Kernel
  sysctl:
    name: net.core.netdev_max_backlog
    value: 5000
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Add nodejs repo keys
  apt_key:
    id: 1655A0AB68576280
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add yarn repo keys
  shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/yarn-archive-keyring.gpg > /dev/null

- name: Add repo for nodejs and yarn
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    - "deb [signed-by=/etc/apt/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main"

- name: Install nodejs, npm and yarn
  apt:
    pkg: ['nodejs', 'yarn']
    state: present

- name: Create HopGlass-server directory if not existent
  file:
    path: /opt/hopglass
    state: directory

- name: Create HopGlass User
  user:
    name: hopglass
    system: yes
    createhome: yes
    home: /opt/hopglass

- name: fix bloody git
  shell: git config --global --add safe.directory /opt/hopglass/server

- name: Clone HopGlass Server Repo
  git:
    repo: https://github.com/ffgtso/hopglass-server.git
    dest: /opt/hopglass/server
    version: ed4d1cd9332720f5f99b29d322cb80b473850193
    force: yes
  notify:
    - "restart hopglass"
  register: hopglass_server_git_clone

- name: Adjust permissions
  file:
    path: /opt/hopglass
    owner: hopglass
    group: hopglass
    recurse: yes
  when: hopglass_server_git_clone.changed

- name: force v4 for yarn install
  blockinfile:
    state: present
    dest: /etc/hosts
    content: |
      104.16.0.35 registry.yarnpkg.com

- name: install dependencies
  shell: yarn install
  args:
    chdir: /opt/hopglass/server
  when: hopglass_server_git_clone.changed

- name: undo force v4 for yarn install
  blockinfile:
    state: absent
    dest: /etc/hosts
    content: |
      104.16.0.35 registry.yarnpkg.com

- name: Create HopGlass-server Config directory if not existent
  file:
    path: /etc/hopglass-server/default
    state: directory

- name: Setup systemd service
  copy:
    src: /opt/hopglass/server/hopglass-server@.service
    dest: /lib/systemd/system/
    remote_src: True

- name: Adjust permissions of /etc/hopglass-server
  file:
    path: /etc/hopglass-server
    owner: hopglass
    group: hopglass
    recurse: yes

- name: Copy config.json
  template: 
    src: config.json.j2 
    dest: /etc/hopglass-server/default/config.json
    owner: hopglass
    group: hopglass
    mode: 0644
  notify:
    - "restart hopglass"

- name: Install jq for delnode script
  apt:
    pkg: jq
    state: present

- name: Copy delnode helper script
  copy:
    src: delnode
    dest: /usr/bin/delnode
    mode: a+x

- name: install hopglass server service hopglass-server
  service: 
    name: hopglass-server@default
    enabled: yes

- name: Install apache2 for privacy filter
  apt:
    pkg: ['apache2']
    state: present

- name: Create /var/www/cgi-bin
  ansible.builtin.file:
    path: /var/www/cgi-bin
    state: directory
    mode: '0755'

- name: Copy apache2 config
  template:
    src: hg-srv-proxy.conf.j2
    dest: /etc/apache2/sites-available/hg-srv-proxy.conf
    mode: 0644
  notify:
   - "restart hopglass"
   - "restart apache2"

- name: Enable
  shell: a2ensite hg-srv-proxy
  notify:
    - "restart apache2"

- name: Enable cgi
  shell: a2enmod cgi
  notify:
    - "restart apache2"

- name: Copy proxy script 1
  copy:
    src: fix_data.shmetrics
    dest: /var/www/cgi-bin/fix_data.shmetrics
    mode: a+x

- name: Copy proxy script 2
  copy:
    src: fix_data.shnodes.json
    dest: /var/www/cgi-bin/fix_data.shnodes.json
    mode: a+x

- name: Copy proxy script 3
  copy:
    src: fix_data.shnodelist.json
    dest: /var/www/cgi-bin/fix_data.shnodelist.json
    mode: a+x

- name: Copy proxy script 4
  copy:
    src: fix_data.shgraph.json
    dest: /var/www/cgi-bin/fix_data.shgraph.json
    mode: a+x
